# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAzygOkn7b_AmUGCRb1oLYxmaYW9ZvyC
"""

!pip install fairlearn

import pandas as pd
import numpy as np

np.random.seed(42)
data = pd.DataFrame({
    "age": np.random.randint(20, 60, 100), # Data 100 kar diya
    "workclass": np.random.choice(["Private", "Gov", "Self"], 100),
    "sex": ["Male"]*50 + ["Female"]*50,
    "hours-per-week": np.random.randint(30, 60, 100),
    # Mix income: Females ko thoda zyada '1' do taaki model seekh sake
    "income": [1]*35 + [0]*15 + [1]*25 + [0]*25
})

data_encoded = pd.get_dummies(data, columns=['workclass', 'sex'], drop_first=True)

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# features aur target alag
X = data.drop('income', axis=1)
y = data['income']

# text ko number me convert
X = pd.get_dummies(X)

# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# model train
model = RandomForestClassifier()
model.fit(X_train, y_train)

print("Model ready ")

from fairlearn.metrics import MetricFrame, selection_rate

# sensitive feature (gender)
sensitive_feature = X_test['sex_Male']

# bias metrics
metrics = {
    "selection_rate": selection_rate
}

metric_frame = MetricFrame(
    metrics=metrics,
    y_true=y_test,
    y_pred=model.predict(X_test),
    sensitive_features=sensitive_feature
)

print(metric_frame.by_group)

from fairlearn.reductions import ExponentiatedGradient, DemographicParity
from sklearn.ensemble import RandomForestClassifier

# naya fair model
mitigator = ExponentiatedGradient(
    RandomForestClassifier(),
    constraints=DemographicParity()
)

# train with fairness
mitigator.fit(X_train, y_train, sensitive_features=X_train['sex_Male'])

# new predictions
y_pred_fair = mitigator.predict(X_test)

print("Fair model ready ")

from fairlearn.metrics import MetricFrame, selection_rate

# BEFORE (old model)
metric_before = MetricFrame(
    metrics={"selection_rate": selection_rate},
    y_true=y_test,
    y_pred=model.predict(X_test),
    sensitive_features=X_test['sex_Male']
)

# AFTER (fair model)
metric_after = MetricFrame(
    metrics={"selection_rate": selection_rate},
    y_true=y_test,
    y_pred=y_pred_fair,
    sensitive_features=X_test['sex_Male']
)

print("Before mitigation:\n", metric_before.by_group)
print("\nAfter mitigation:\n", metric_after.by_group)